// Welcome to Dittytoy!
//
// Dittytoy is a community for creative coding. We believe the joy 
// is in the craft. 
//
// ---------------------------------------------------------------
// A NOTE ON AI:
// Please do not publish code entirely generated by AI. 
// We want to see YOUR creativity, your mistakes, and your logic. 
// If you use AI to learn, try to rewrite the code yourself before 
// sharing, so others can learn from your human approach.
// ---------------------------------------------------------------
//
// API Reference: https://dittytoy.net/syntax
// Example ditties: https://dittytoy.net/user/Dittytoy

ditty.bpm = 120;

function tri(p) {
    p %= 1;
    return p < 0.5 ? 1 - 4 * p : 4*p - 3;
}

function bturn(p, dt) {
    let x = Math.abs(p / dt);
    if(x <= 1 && x > 0)
        return (x*x-2*x+1) * 2 * dt;
    else
        return 0;
}

let frc = x => x - Math.floor(x);

// Triangle synth
const triangle = synth.def( (phase, env, time, opt) => (
    tri(phase)
    + bturn(frc(phase) - .5, midi_to_hz(opt.note) * ditty.dt)
    - bturn(frc(phase+.5)-.5, midi_to_hz(opt.note) * ditty.dt)
    
    ) * env.value );

// Example of a simple stereo low-pass filter
const lpf = filter.def(class {
    constructor(options) {
        this.l = 0;
        this.r = 0;
    }
    process(input, options) {
        this.l += (input[0] - this.l) * options.cutoff;
        this.r += (input[1] - this.r) * options.cutoff;
        return [this.l, this.r];
    }
}, { cutoff: 0.1 });

input.f = 0; //min=20,max=20000,step=1

// Main loop, connected to the filter we just created
triangle.play(()=>hz_to_midi(input.f), { attack: 0.01, release: 0.75,  duration: 1000.25 });
